# Site settings
title: RAWISH CARE BRIDGE TRUST 1
description: This is a test page for now 1
cover: assets/images/hcm-restingtime-pic.png
logo: assets/images/rw-logo-tpnt.png
favicon: assets/images/rawishtrust-logo.png
baseurl: "" # the subpath of your site, e.g. /blog/ or / for root
#url: "https://github.com/urmsandeep/rt3test" # the base hostname & protocol for your site
url: "https://urmsandeep.github.io/rt3test.github.io/"

pagination:

  # Site-wide kill switch, disabled here it doesn't run at all
  enabled: true

  # Set to 'true' to enable pagination debugging. This can be enabled in the site config or only for individual pagination pages
  debug: false

  per_page: 5

# Social
facebook: facebook
twitter: twitter
github:  github

#Additional Pages
about: about
contact: contact
privacy-policy: privacy-policy
aboutus: aboutus



permalink: /:title


# Google Analytics
analytics_id: ""

# Build settings
markdown: kramdown

kramdown:
  parse_block_html: true

plugins:
  - jekyll-paginate-v2


# Settings for rake task
safe: False
lsi: False
username: rt3 #github username
repo: rt3test #github repository
branch: master #branch
relative_source: ../rt3test/ #source directory
destination: ../rt3test-pages/ #destination directory
production_url: https://github.com/urmsandeep/rt3test
source_url:  https://github.com/urmsandeep/rt3test #source repository url

exclude:
  - README.md
  - Rakefile
  - Gemfile
  - Gemfile.lock
  - changelog.md
  - "*.Rmd"
  - vendor
  - .travis.yml
